name: Format Check

on:
  - push
  - pull_request


jobs:
  ci:
    name: format-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-12
      - name: Check formatting
        run: ./tools/clang-format-check.sh
